name: My first github action 
on: [push]

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - run: echo "Hello Dishant!"
        - run: pwd 
        - run: whoami 
        - run: git --version 
        - run: uname -a 
        
      


    
